change docker login steps

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -17,9 +17,8 @@ jobs:
       - name: Build
         run: | 
           ssh -o ServerAliveInterval=60 ${{ secrets.BUILD_SSH_USER }}@${{ secrets.BUILD_SSH_HOST }} -p ${{ secrets.BUILD_SSH_PORT }} \
-          "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} \
-          DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }} \
-          cd ${{ secrets.BUILD_WORKDIR }} && ./build.sh"
+          'echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin || { echo "Failed to docker login" && exit 1; } \
+          cd '"${{ secrets.BUILD_WORKDIR }}"' && ./build.sh'
       - name: Clean Up
         run: rm -rf ~/.ssh
   
